# Rustfmt configuration file
# See the full list of options at: https://rust-lang.github.io/rustfmt/

# Specify the Rust edition to use
# Options: 2015, 2018, 2021
edition = "2021"
max_width = 100
tab_spaces = 4
hard_tabs = false
newline_style = "Unix"
use_small_heuristics = "Max"

fn_params_layout = "Compressed"
reorder_impl_items = true
merge_derives = true
use_field_init_shorthand = true

reorder_imports = true
reorder_modules = true

control_brace_style = "AlwaysSameLine"
match_block_trailing_comma = true

error_on_line_overflow = false
